# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            "BIO 593 Class Website"
tagline:          'Special Topics In R'
description:      'This is the class website for BIO 593: Special Topics in R.  Class materials, developed by students, will live here and will cover a variety of topics on using R for data science.'
url:              https://rhodyrstats.github.io/special_topics_in_r
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'rhodyRstats'
  url:            https://twitter.com/rhodyRstats

paginate:         5
paginate_path:    ''
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/rhodyrstats/special_topics_in_r
